# Generated by Django 2.2.3 on 2019-07-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VipPermissions',
            new_name='VipPermission',
        ),
    ]
